name: ci-cpu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        jobname: [MiniVATES-serial, MiniVATES-threads]
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Action
        uses: actions/checkout@v4

      - name: Instantiate
        run: |
          which julia || curl -fsSL https://install.julialang.org | sh -s -- -y
          . /home/runner/.bashrc
          julia --project -e 'using Pkg; Pkg.add(name="JACC", rev="main")'

      - name: Test Serial
        if: contains(matrix.jobname, '-serial')
        run: julia --project -e 'using Pkg; Pkg.test()'

      - name: Test Threads
        if: contains(matrix.jobname, '-threads')
        run: julia -t 4 --project -e 'using Pkg; Pkg.test()'

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        jobname: [MiniVATES-serial, MiniVATES-threads]

    steps:
      - name: Checkout Action
        uses: actions/checkout@v4

      - name: Instantiate
        run: |
          brew install julia
          julia --project -e 'using Pkg; Pkg.add(name="JACC", rev="main")'

      - name: Test Serial
        if: contains(matrix.jobname, '-serial')
        run: julia --project -e 'using Pkg; Pkg.test()'

      - name: Test Threads
        if: contains(matrix.jobname, '-threads')
        run: julia -t 3 --project -e 'using Pkg; Pkg.test()'
